### ISSUE TITLE
フォルダを移動した後一度しか動作しない

### ISSUE THREAD

**Issue by pklion** [hebiiro/AviUtl-Plugin-BigDialog#2]
BigDialog.aul を導入した際、
① plugins フォルダーに導入
② AviUtl を起動 (BigDialog が動作したか確認忘れました)
③ 2度目に起動 (BigDialog 動作せず)
④ plugins フォルダー → 1つ上の階層へ
⑤ AviUtl を起動 (BigDialog 動作した)
⑥ 2度目に起動 (BigDialog 動作せず)
⑦ aviutl.exe の階層 → plugins フォルダーに
⑧ AviUtl を起動 (BigDialog 動作した)
⑨ 2度目に起動 (BigDialog 動作せず)
…
を繰り返します
よければ改善頂けると嬉しいです。

**Comment by hebiiro** [comment]
未だ解決方法がわかってないです；；

**Comment by pklion** [comment]
了解です…
とても有り難い機能だな、と思っているので、取り敢えず交互に動かしながら使用しようと思います。もし改善方法が見つかった際には更新いただければと思います。(こちら側でも解決方法を探ってみます)
対応ありがとうございます！

**Comment by hebiiro** [comment]
2.0.0 で解消できたかもしれないので試してみてください。

**Comment by pklion** [comment]
さすが蛇色さん…！
軽くチェックしてみたところ、現時点ではこちらでも動作しています。本当にありがとうございました。
また不具合等あれば書かせていただければと思っております。
