### ISSUE TITLE
新しいプロジェクトを作成するとき4桁以上のサイズを設定出来なくなる

### ISSUE THREAD

**Issue by teatime59** [hebiiro/AviUtl-Plugin-BigDialog#3]
開発お疲れ様です、Issuesというものを人生で初めて送らせていただきます
新しいプロジェクトを作成するとき4桁以上の数字を打てなくなることが分かりました
1280×720にサイズを変更しようとしたところ128×720のプロジェクトになってしまいます
このプラグインだけ抜くと改善したので原因はこのプラグインだと考えています
修正いただけたら幸いです

**Comment by hebiiro** [comment]
3.0.0で修正しました。

**Comment by teatime59** [comment]
> 

素早い対応感謝します！
これからも応援しています
